- name: Include prepare tasks specific for distribution and architecture
  include_tasks: '{{ item }}'
  vars:
    params:
      files:
        - 'prepare-{{ ansible_distribution }}-{{ ansible_architecture }}.yml'
        - 'prepare-{{ ansible_distribution }}.yml'
  loop: "{{ q('first_found', params, errors='ignore') }}"

- name: Clear yum versionlocks
  command: yum versionlock clear
  args:
    warn: no
  when: 'leapp_yum_version_locked | default() | bool'

- name: Install required LEAPP packages
  package:
    name: '{{ leapp_packages }}'
    state: present
  when: 'not leapp_skip_prepare_package_install | bool'

- name: Install LEAPP module for cockpit
  package:
    name: '{{ leapp_packages_cockpit }}'
    state: present
  notify:
    - restart cockpit
  when:
    - 'not leapp_skip_prepare_cockpit_install | bool'
  register: leapp_package_cockpit

- name: Update all packages to latest # noqa 403
  package:
    name: '*'
    state: latest
  register: leapp_package_update
  when:
    - 'not leapp_skip_prepare_update | bool'

- name: Reboot system # noqa 503
  block:
    - debug:
        msg: "Rebooting system"
      notify:
        - reboot system
  when:
    - 'leapp_package_update.changed'
    - 'not leapp_skip_prepare_update_reboot | bool'

- name: Force all notified handlers to run at this point, not waiting for normal sync points
  meta: flush_handlers
